---
# Warp Terminal Configuration
# Enhanced settings for dotfiles management

# AI Context Settings
ai_suggestions:
  context_aware: true
  prefer_aliases: true
  learn_from_usage: true

# Environment context
environment_rules:
  dotfiles:
    directories:
      - "$HOME"
      - "$HOME/.config"  
      - "$HOME/.local"
      - "$HOME/.dotfiles"
    preferred_commands:
      git: "dot"
      "git status": "ds"
      "git add": "da"
      "git commit": "dc"
      "git push": "dp"
      "git pull": "dl"
      "git diff": "dd"

# Completion preferences
completions:
  git_context_aware: true
  prefer_shortened_commands: true
