
# tap repositories and their packages

tap homebrew/core
brew adwaita-icon-theme
brew antidote
brew aom
brew aria2
brew aribb24
brew awk
brew bash
brew bash-completion
brew bat
brew bat-extras
brew blueutil
brew brightness
brew broot
brew brotli
brew btop
brew ca-certificates
brew cairo
brew certifi
brew cjson
brew cmake
brew coreutils
brew curl
brew czkawka
brew dav1d
brew dbus
brew defaultbrowser
brew deno
brew diff-so-fancy
brew diffutils
brew exiftool
brew eza
brew fastfetch
brew fd
brew ffmpeg
brew ffmpeg@6
brew findutils
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gallery-dl
brew gawk
brew gd
brew gdk-pixbuf
brew gettext
brew gh
brew giflib
brew gifski
brew git
brew git-delta
brew git-extras
brew git-gui
brew git-tools
brew glib
brew glow
brew gmp
brew gnu-tar
brew gnu-which
brew gnupg
brew gnutls
brew go
brew goku
brew gomi
brew graphene
brew graphite2
brew graphviz
brew gtk4
brew gts
brew gum
brew harfbuzz
brew hicolor-icon-theme
brew highway
brew icu4c@77
brew imagemagick
brew imath
brew imessage-exporter
brew jasper
brew jdupes
brew joker
brew jpeg-turbo
brew jpeg-xl
brew jq
brew khard
brew lame
brew leptonica
brew less
brew libarchive
brew libass
brew libassuan
brew libavif
brew libb2
brew libbluray
brew libde265
brew libdeflate
brew libepoxy
brew libevent
brew libgcrypt
brew libgit2
brew libgpg-error
brew libheif
brew libidn2
brew libimobiledevice
brew libimobiledevice-glue
brew libksba
brew liblinear
brew liblqr
brew libmicrohttpd
brew libnghttp2
brew libogg
brew libomp
brew libplist
brew libpng
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libusbmuxd
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lua
brew lynis
brew lz4
brew lzo
brew m4
brew mas
brew mbedtls
brew micro
brew mise
brew moreutils
brew most
brew mpdecimal
brew mpfr
brew mpg123
brew ncdu
brew ncurses
brew netpbm
brew nettle
brew nmap
brew npth
brew ollama
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openssl@3
brew opus
brew p11-kit
brew p7zip
brew pandoc
brew pango
brew pcre2
brew pinentry
brew pixman
brew pkgconf
brew popt
brew portaudio
brew powerlevel10k
brew prettyping
brew procs
brew python@3.13
brew rav1e
brew readline
brew rich-cli
brew ripgrep
brew rlwrap
brew rsync
brew rtmpdump
brew rubberband
brew ruby
brew s-lang
brew scooter
brew sd
brew sdl2
brew shared-mime-info
brew shellcheck
brew shfmt
brew snappy
brew speedtest-cli
brew speex
brew spoof-mac
brew spotifyd
brew sqlite
brew srt
brew starship
brew superfile
brew svt-av1
brew syncthing
brew tcl-tk@8
brew tealdeer
brew telegram-downloader
brew tesseract
brew theora
brew tmux
brew topgrade
brew tree
brew unbound
brew usage
brew utf8proc
brew uv
brew watch
brew watchexec
brew webp
brew webp-pixbuf-loader
brew wget
brew x264
brew x265
brew xdg-ninja
brew xorgproto
brew xsel
brew xvid
brew xxhash
brew xz
brew zeromq
brew zimg
brew zoxide
brew zsh
brew zstd

tap homebrew/cask
cask alifix
cask alisma
cask apparency
cask betterdisplay
cask blockblock
cask cirrus
cask claude
cask clay
cask cryptomator
cask etrecheckpro
cask font-fira-code
cask font-fira-code-nerd-font
cask font-hack
cask font-meslo-lg-nerd-font
cask font-new-york
cask font-overpass
cask font-recursive
cask font-recursive-code
cask font-rubik
cask github
cask google-chrome
cask google-drive
cask imageoptim
cask itunes-volume-control
cask jordanbaird-ice
cask jpc-qlcolorcode
cask jump-desktop-connect
cask keka
cask keybase
cask keyboard-cowboy
cask keyclu
cask knockknock
cask legcord
cask localsend
cask logitune
cask markedit
cask metamer
cask notion
cask notunes
cask obsidian
cask pearcleaner
cask privileges
cask qlmarkdown
cask qlprettypatch
cask qlstephen
cask qlvideo
cask quicklook-csv
cask quicklook-json
cask raindropio
cask raycast
cask secretive
cask shortcat
cask shortwave
cask signal
cask swiftdefaultappsprefpane
cask swish
cask syntax-highlight
cask telegram
cask telegram-desktop@beta
cask visual-studio-code
cask warp
cask warp@preview
cask wordservice
cask xattred

tap homebrew/command-not-found

tap avpres/formulae
brew bash-avpres

tap basicmachines-co/basic-memory
brew basic-memory

tap bendews/tap
brew apw

tap bepaald/signalbackup-tools
brew signalbackup-tools --HEAD

tap buo/cask-upgrade

tap dimentium/autoraise
cask autoraiseapp

tap doron-cohen/tap
brew antidot

tap iina/mpv-iina

tap lihaoyun6/tap

tap loteoo/formulas
brew ks

tap lukechilds/tap
brew chest

tap martido/graph

tap rcmdnk/file
brew brew-file

tap tabbyml/tabby
brew tabby

tap taylorwilsdon/tap
brew reclaimed

tap tbvdm/tap
brew sigtop --HEAD

tap vitorgalvao/tiny-scripts
brew tape

tap yqrashawn/goku

# App Store applications
appstore 1586435171 Actions (3.8.0)
appstore 1659667937 Actions For Obsidian (2025.1.0)
appstore 1037126344 Apple Configurator (2.18)
appstore 1518425043 Boop (1.4.0)
appstore 1632827132 Camera Preview (1.7.4)
appstore 1472875808 CardPointers (6.5.1)
appstore 1545870783 Color Picker (2.1.2)
appstore 1198176727 ControllerForHomeKit (7.6.3)
appstore 1447330651 Copilot (6.0.6)
appstore 1552415914 Couverture (1.5)
appstore 953286746 Darkroom (6.8.19)
appstore 1453273600 Data Jar (1.1.4)
appstore 1355679052 Dropover (5.0.4)
appstore 1615988943 Folder Peek (1.12.0)
appstore 6698876601 Folder Preview (1.8.7)
appstore 6443796196 FreeScaler (1.0.1)
appstore 1351639930 Gifski (2.23.1)
appstore 6737538832 HEVCut (1.7.25)
appstore 1462943921 Hue Essentials (4.3.7)
appstore 6444667067 Hyperduck (1.3.0)
appstore 6739505345 Hyperspace (1.3.4)
appstore 6444915884 Ice Cubes (1.11.3)
appstore 6446206067 Klack (1.7.2)
appstore 441258766 Magnet (3.0.7)
appstore 6747118113 MDSynthesizer (0.0.2)
appstore 1440405750 MusicHarbor (5.0.4)
appstore 1630766571 MyApplications (1.0.2)
appstore 409203825 Numbers (14.4)
appstore 6720708363 Obsidian Web Clipper (0.11.8)
appstore 1499215709 Pasteboard Viewer (2.10.1)
appstore 6714467650 Perplexity (2.250710.0)
appstore 6739038077 PhotoSort (1.11)
appstore 6739781207 Pieoneer (1.15)
appstore 1289583905 Pixelmator Pro (3.7)
appstore 1459275972 Playlisty for Apple Music (3.30)
appstore 6478105775 Playlisty for Spotify (1.23)
appstore 1660037028 PreviewText (1.0.9)
appstore 545519333 Prime Video (10.86)
appstore 6748257094 Project Ingest (1.0.0)
appstore 1611378436 Pure Paste (1.12.2)
appstore 6738274497 Raycast Companion (1.1.1)
appstore 1546140065 RegExp (2.2.1)
appstore 6504040051 Scratchpad (1.3.7)
appstore 1344679160 Scrobbles for Last.fm (9.3.5)
appstore 1522267256 Shareful (1.11.0)
appstore 1564015476 ShellHistory (3.0)
appstore 1594183810 Shortery (8.0)
appstore 1006087419 SnippetsLab (2.6.1)
appstore 1296723195 Startup Manager (2.6.0)
appstore 6449814769 swipefy_app (2.8.2)
appstore 6744716215 TaskForge (1.8.2)
appstore 946399090 Telegram Lite (5.16.5)
appstore 899247664 TestFlight (3.9.0)
appstore 1492174677 Text Case (2023.3)
appstore 6739804295 Tuneful (2.7.0)
appstore 1211437633 Universe​ (2025.27)
appstore 6477287463 Unwatched (1.6.5)
appstore 1607635845 Velja (2.1.3)
appstore 1518836004 Video Converter (1.1.7)
appstore 1524540481 Widgy (4.0.2)
appstore 6738340521 ZeroDuplicates (1.9.1)

# VSCode extensions
vscode adguard.adblock
vscode aspel.github-sync-fork
vscode automatalabs.copilot-mcp
vscode bmalehorn.shell-syntax
vscode chouzz.vscode-better-align
vscode chrmarti.regex
vscode davidanson.vscode-markdownlint
vscode dennykorsukewitz.githubfilefetcher
vscode donjayamanne.githistory
vscode dotiful.dotfiles-syntax-highlighting
vscode dual.zsh-completion-script
vscode eamodio.gitlens
vscode editorconfig.editorconfig
vscode edwinhuish.better-comments-next
vscode edwinkofler.vscode-assorted-languages
vscode fabiospampinato.vscode-diff
vscode foxundermoon.shell-format
vscode gitguardian-secret-security.gitguardian
vscode github.copilot
vscode github.copilot-chat
vscode github.remotehub
vscode guttih.sheller
vscode henriquebruno.github-repository-manager
vscode hverlin.mise-vscode
vscode idleberg.applescript
vscode jeff-hykin.better-shellscript-syntax
vscode jmallien.replacewithnewline
vscode l13rary.l13-sh-snippets
vscode ldez.ignore-files
vscode lonr.sort-settings-json
vscode lunarlimbo.banner-comments-plus
vscode maciejdems.add-to-gitignore
vscode mads-hartmann.bash-ide-vscode
vscode mhutchie.git-graph
vscode miguelsolorio.symbols
vscode mkhl.shfmt
vscode ms-python.debugpy
vscode ms-python.python
vscode ms-python.vscode-pylance
vscode ms-vscode.remote-repositories
vscode ms-vscode.vscode-commander
vscode ms-windows-ai-studio.windows-ai-studio
vscode mxthevs.one-dark-pro-monokai-darker-reloaded
vscode oderwat.indent-rainbow
vscode oliverdantzer.file-structure-tree
vscode openai.chatgpt
vscode polymermallard.box-comment
vscode remcohaszing.schemastore
vscode rooveterinaryinc.roo-cline
vscode rpinski.shebang-snippets
vscode ryu1kn.partial-diff
vscode saoudrizwan.claude-dev
vscode shaharkazaz.git-merger
vscode shd101wyy.markdown-preview-enhanced
vscode shellomo.enhanced-toml
vscode sidneys1.gitconfig
vscode sleistner.vscode-fileutils
vscode specstory.specstory-vscode
vscode stevebeauge.quick-toggle-hide-ignored-files
vscode tamasfe.even-better-toml
vscode timonwong.shellcheck
vscode tkoresearch.applescript-support
vscode usernamehw.errorlens
vscode vsls-contrib.gitdoc
vscode waseemakram.bashnsippets
vscode wenfangdu.snippet-generator
vscode yatki.vscode-surround
vscode yy0931.gitconfig-lsp
vscode yzhang.markdown-all-in-one
vscode zokugun.cron-tasks
vscode zokugun.sync-settings
