#!/usr/bin/env sh

# Function: h-clean()
#
# Description:
#   Fixes the history file by removing any bad characters
#
# shellcheck disable=SC2168

#h-clean(){
    local tmp_histfile="${~HISTFILE}"_bad
    mv -iv $HISTFILE $tmp_histfile
    strings $tmp_histfile > $HISTFILE
    fc -R $HISTFILE
    /bin/rm -rf $tmp_histfile
#}
