#!/bin/zsh

# Automatically dump current Brewfile if changes are made to the system
# Functions are available to execute just like commands.
# Mostly stolen from: https://github.com/Homebrew/brew/issues/3933#issuecomment-373771217

local dump_commands=('install' 'uninstall' 'remove' 'reinstall' 'untap') # Include all commands that should do a brew dump
local main_command="${1}"
  
brew ${@}
#"$HOMEBREW_PREFIX/bin/brew" ${@}

for command in "${dump_commands[@]}"; do
  [[ "${command}" == "${main_command}" ]] && brew bundle dump --force --no-upgrade -all --file="${XDG_CONFIG_HOME:-$HOME/.config}/homebrew/init.brewfile"
done